### ISSUE TITLE
Make the algorithm return events for the same day

### ISSUE THREAD

**Issue by marksteward** [pubstandards/pubstandards-london#7]
Basically to make these tests work:

  https://github.com/pubstandards/pubstandards-london/blob/7445ba9/tests/test_ps_data.py#L93-L97

Need to make sure we've got appropriate regression tests in place.

**Comment by Jonty** [comment]
Hm, thought I'd tested that, must have broken it. Will look into it.

**Comment by Jonty** [comment]
Fixed by d48b4d9 and b23f836 in jonty/the_algorithm.

**Comment by marksteward** [comment]
No need for regression tests. The algorithm is authoritative. TRUST THE ALGORITHM.

**Comment by Jonty** [comment]
I trusted the tests you wrote!
